package vial;
import sys.io.File;
import tools.ERegTools;

/**
 * How to run (from src/:)
 * haxe --neko vial/VialKeyNamesGen.n -main vial.VialKeyNamesGen
 * neko vial/VialKeyNamesGen.n
 * @author YellowAfterlife
 */
class VialKeyNamesGen {
	public static function main() {
		var py = File.getContent("vial/keycodes.py");
		var b = new StringBuf();
		for (line in [
			"package vial;",
			"/** ",
			" * Generated by VialKeyNamesGen.hx",
			" * from vial-kb/vial-gui: src/main/python/keycodes/keycodes.py",
			" */",
			"class VialKeyNames {",
			"	public static var map:Map<String, String> = ["
		]) b.add(line + "\r\n");
		ERegTools.each(~/^\s*K\((".+?"), (".+?"),.+/gm, py, function(rx:EReg) {
			b.add("\t\t" + rx.matched(1) + " => " + rx.matched(2) + ",\r\n");
		});
		b.add("\t];\r\n");
		b.add("}\r\n");
		File.saveContent("vial/VialKeyNames.hx", b.toString());
		Sys.println("OK!");
	}
}